# Generated by Django 2.1.1 on 2018-09-02 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessibilityForDisabilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_id', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_id', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Eligibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_id', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Funding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_id', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='HolidayScheduleAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_id', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_id', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_id', models.CharField(max_length=200)),
                ('name', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_id', models.CharField(max_length=200)),
                ('name', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PaymentAccepted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_id', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_id', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PhysicalAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_id', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PostalAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_id', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_id', models.CharField(max_length=200)),
                ('name', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=200, unique=True)),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RegularScheduleAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_id', models.CharField(max_length=200)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orseal_engine.Project')),
            ],
        ),
        migrations.CreateModel(
            name='RequiredDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_id', models.CharField(max_length=200)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orseal_engine.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_id', models.CharField(max_length=200)),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orseal_engine.Project')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_id', models.CharField(max_length=200)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orseal_engine.Project')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceAtLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_id', models.CharField(max_length=200)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orseal_engine.Project')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceTaxonomy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_id', models.CharField(max_length=200)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orseal_engine.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Taxonomy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_id', models.CharField(max_length=200)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orseal_engine.Project')),
            ],
        ),
        migrations.AddField(
            model_name='program',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orseal_engine.Project'),
        ),
        migrations.AddField(
            model_name='postaladdress',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orseal_engine.Project'),
        ),
        migrations.AddField(
            model_name='physicaladdress',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orseal_engine.Project'),
        ),
        migrations.AddField(
            model_name='phone',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orseal_engine.Project'),
        ),
        migrations.AddField(
            model_name='paymentaccepted',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orseal_engine.Project'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orseal_engine.Project'),
        ),
        migrations.AddField(
            model_name='location',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orseal_engine.Project'),
        ),
        migrations.AddField(
            model_name='language',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orseal_engine.Project'),
        ),
        migrations.AddField(
            model_name='holidayscheduleaddress',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orseal_engine.Project'),
        ),
        migrations.AddField(
            model_name='funding',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orseal_engine.Project'),
        ),
        migrations.AddField(
            model_name='eligibility',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orseal_engine.Project'),
        ),
        migrations.AddField(
            model_name='contact',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orseal_engine.Project'),
        ),
        migrations.AddField(
            model_name='accessibilityfordisabilities',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orseal_engine.Project'),
        ),
    ]
